server:
  port: 8888
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mariadb://localhost:3306/study_cafe?characterEncoding=UTF-8$ServerTime=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

logging:
  level:
    root: info
    org:
      hibernate:
        type: debug


app:
  filePath: C:\Users\laon-04\IdeaProjects\board\src\main\uploadFile